name:                opencl-b
version:             1.2.0.1
github:              "emekoi/opencl-b"
license:             BSD3
author:              "Emeka Nkurumeh"
maintainer:          "emekankurumeh@outlook.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/emekoi/opencl-b#readme>

dependencies:
- base >= 4.7 && < 5
- bindings-OpenCL == 1.2.0.1
- template-haskell >= 2.15.0.0

default-extensions:
  - FlexibleInstances
  - MultiParamTypeClasses
  - FlexibleContexts
  - TupleSections
  - LambdaCase

library:
  source-dirs: src

tests:
  opencl-b-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - opencl-b
